if (Test-Path alias:arch) { Remove-Alias -Name arch -Scope Global }
if (Test-Path alias:base32) { Remove-Alias -Name base32 -Scope Global }
if (Test-Path alias:base64) { Remove-Alias -Name base64 -Scope Global }
if (Test-Path alias:basename) { Remove-Alias -Name basename -Scope Global }
if (Test-Path alias:cat) { Remove-Alias -Name cat -Scope Global }
if (Test-Path alias:cksum) { Remove-Alias -Name cksum -Scope Global }
if (Test-Path alias:comm) { Remove-Alias -Name comm -Scope Global }
if (Test-Path alias:cp) { Remove-Alias -Name cp -Scope Global }
if (Test-Path alias:cut) { Remove-Alias -Name cut -Scope Global }
if (Test-Path alias:date) { Remove-Alias -Name date -Scope Global }
if (Test-Path alias:df) { Remove-Alias -Name df -Scope Global }
if (Test-Path alias:dircolors) { Remove-Alias -Name dircolors -Scope Global }
if (Test-Path alias:dirname) { Remove-Alias -Name dirname -Scope Global }
if (Test-Path alias:echo) { Remove-Alias -Name echo -Scope Global }
if (Test-Path alias:env) { Remove-Alias -Name env -Scope Global }
if (Test-Path alias:expand) { Remove-Alias -Name expand -Scope Global }
if (Test-Path alias:expr) { Remove-Alias -Name expr -Scope Global }
if (Test-Path alias:factor) { Remove-Alias -Name factor -Scope Global }
if (Test-Path alias:false) { Remove-Alias -Name false -Scope Global }
if (Test-Path alias:fmt) { Remove-Alias -Name fmt -Scope Global }
if (Test-Path alias:fold) { Remove-Alias -Name fold -Scope Global }
if (Test-Path alias:hashsum) { Remove-Alias -Name hashsum -Scope Global }
if (Test-Path alias:head) { Remove-Alias -Name head -Scope Global }
if (Test-Path alias:hostname) { Remove-Alias -Name hostname -Scope Global }
if (Test-Path alias:join) { Remove-Alias -Name join -Scope Global }
if (Test-Path alias:link) { Remove-Alias -Name link -Scope Global }
if (Test-Path alias:ln) { Remove-Alias -Name ln -Scope Global }
if (Test-Path alias:ls) { Remove-Alias -Name ls -Scope Global }
if (Test-Path alias:md5sum) { Remove-Alias -Name md5sum -Scope Global }
if (Test-Path alias:mkdir) { Remove-Alias -Name mkdir -Scope Global }
if (Test-Path alias:mktemp) { Remove-Alias -Name mktemp -Scope Global }
if (Test-Path alias:more) { Remove-Alias -Name more -Scope Global }
if (Test-Path alias:mv) { Remove-Alias -Name mv -Scope Global }
if (Test-Path alias:nl) { Remove-Alias -Name nl -Scope Global }
if (Test-Path alias:nproc) { Remove-Alias -Name nproc -Scope Global }
if (Test-Path alias:od) { Remove-Alias -Name od -Scope Global }
if (Test-Path alias:paste) { Remove-Alias -Name paste -Scope Global }
if (Test-Path alias:printenv) { Remove-Alias -Name printenv -Scope Global }
if (Test-Path alias:printf) { Remove-Alias -Name printf -Scope Global }
if (Test-Path alias:ptx) { Remove-Alias -Name ptx -Scope Global }
if (Test-Path alias:pwd) { Remove-Alias -Name pwd -Scope Global }
if (Test-Path alias:readlink) { Remove-Alias -Name readlink -Scope Global }
if (Test-Path alias:realpath) { Remove-Alias -Name realpath -Scope Global }
if (Test-Path alias:relpath) { Remove-Alias -Name relpath -Scope Global }
if (Test-Path alias:rm) { Remove-Alias -Name rm -Scope Global }
if (Test-Path alias:rmdir) { Remove-Alias -Name rmdir -Scope Global }
if (Test-Path alias:seq) { Remove-Alias -Name seq -Scope Global }
if (Test-Path alias:sha1sum) { Remove-Alias -Name sha1sum -Scope Global }
if (Test-Path alias:sha224sum) { Remove-Alias -Name sha224sum -Scope Global }
if (Test-Path alias:sha256sum) { Remove-Alias -Name sha256sum -Scope Global }
if (Test-Path alias:sha3-224sum) { Remove-Alias -Name sha3-224sum -Scope Global }
if (Test-Path alias:sha3-256sum) { Remove-Alias -Name sha3-256sum -Scope Global }
if (Test-Path alias:sha3-384sum) { Remove-Alias -Name sha3-384sum -Scope Global }
if (Test-Path alias:sha3-512sum) { Remove-Alias -Name sha3-512sum -Scope Global }
if (Test-Path alias:sha384sum) { Remove-Alias -Name sha384sum -Scope Global }
if (Test-Path alias:sha3sum) { Remove-Alias -Name sha3sum -Scope Global }
if (Test-Path alias:sha512sum) { Remove-Alias -Name sha512sum -Scope Global }
if (Test-Path alias:shake128sum) { Remove-Alias -Name shake128sum -Scope Global }
if (Test-Path alias:shake256sum) { Remove-Alias -Name shake256sum -Scope Global }
if (Test-Path alias:shred) { Remove-Alias -Name shred -Scope Global }
if (Test-Path alias:shuf) { Remove-Alias -Name shuf -Scope Global }
if (Test-Path alias:split) { Remove-Alias -Name split -Scope Global }
if (Test-Path alias:sum) { Remove-Alias -Name sum -Scope Global }
if (Test-Path alias:sync) { Remove-Alias -Name sync -Scope Global }
if (Test-Path alias:tac) { Remove-Alias -Name tac -Scope Global }
if (Test-Path alias:tail) { Remove-Alias -Name tail -Scope Global }
if (Test-Path alias:test) { Remove-Alias -Name test -Scope Global }
if (Test-Path alias:touch) { Remove-Alias -Name touch -Scope Global }
if (Test-Path alias:tr) { Remove-Alias -Name tr -Scope Global }
if (Test-Path alias:true) { Remove-Alias -Name true -Scope Global }
if (Test-Path alias:truncate) { Remove-Alias -Name truncate -Scope Global }
if (Test-Path alias:tsort) { Remove-Alias -Name tsort -Scope Global }
if (Test-Path alias:unexpand) { Remove-Alias -Name unexpand -Scope Global }
if (Test-Path alias:uniq) { Remove-Alias -Name uniq -Scope Global }
if (Test-Path alias:wc) { Remove-Alias -Name wc -Scope Global }
if (Test-Path alias:whoami) { Remove-Alias -Name whoami -Scope Global }
if (Test-Path alias:yes) { Remove-Alias -Name yes -Scope Global }
if (Test-Path alias:ps) { Remove-Alias -Name ps -Scope Global }
