;;; -*- lexical-binding: t; -*-

(defun my/isearch-region ()
  (interactive)
  (isearch-forward nil 1)
  (when (use-region-p)
    (let ((beg (region-beginning))
          (end (region-end)))
      (deactivate-mark)
      (goto-char beg)    
      (isearch-yank-string (buffer-substring-no-properties beg end))
      (isearch-done)
      (isearch-lazy-highlight-new-loop))))

(defun my/isearch-forward-region ()
  (interactive)
  (if (use-region-p)
      (my/isearch-region)
    (isearch-repeat-forward 1)))

(defun my/isearch-backward-region ()
  (interactive)
  (if (use-region-p)
      (my/isearch-region)
    (isearch-repeat-backward 1)))
