version: '3'

networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo/forgejo:1.21
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - forgejo
    volumes:
      - ./data:/data
      - ./timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '1234:1234'
      - '2222:2222'
