(defun set-mark-sexp (&optional arg)
  (interactive)
  (setq arg (or arg 1))
  (sp-mark-sexp)
  (exchange-point-and-mark)
  (deactivate-mark)
  (sp-backward-sexp)
  (sp-mark-sexp)
  (when (> arg 0)
    (exchange-point-and-mark)
    (backward-char)))

(defun deactivate-mark-command ()
  (interactive)
  (if (region-active-p)
      (deactivate-mark)))

(defun mark-whole-line-to-next (&optional arg)
  (interactive)
  (setq arg (or arg 1))
  (end-of-line)
  (unless (use-region-p)
    (set-mark (line-beginning-position)))
  (forward-line arg))

(defun mark-whole-line-to-previous (&optional arg)
  (interactive)
  (mark-whole-line-to-next (- (or arg 1))))

(provide 'text-object)
