{ ... }:
{
  imports = [
    ./agenix.nix
    ./autorandr.nix
    ./brave.nix
    ./cloudflare-warp.nix
    ./code.nix
    ./copy-file.nix
    ./dunst.nix
    ./fontconfig.nix
    ./fonts.nix
    ./i3wm.nix
    ./jamesdsp.nix
    ./loopback-toggle.nix
    ./micro.nix
    ./pacman.nix
    ./picom.nix
    ./polybar.nix
    ./qview.nix
    ./rofi.nix
    ./scaling.nix
    ./screenshot.nix
    ./script.nix
    ./shell.nix
    ./sublime.nix
    ./telegram.nix
    ./themes.nix
    ./wezterm.nix
    ./xdg-desktop-portal.nix
  ];
}
