{ ... }:
{
  imports = [
    ./agenix.nix
    ./alacritty.nix
    ./autorandr.nix
    ./betterlockscreen.nix
    ./browser.nix
    ./bspwm.nix
    ./cloudflare-warp.nix
    ./codium.nix
    ./copy-file.nix
    ./dunst.nix
    ./fontconfig.nix
    ./fonts.nix
    ./loopback-toggle.nix
    ./micro.nix
    ./picom.nix
    ./polybar.nix
    ./qview.nix
    ./rofi.nix
    ./scaling.nix
    ./screenshot.nix
    ./shell.nix
    ./sxhkd.nix
    ./themes.nix
    ./xdg-portal.nix
  ];
}
