;;; -*- lexical-binding: t; -*-

(defun my/consult-lsp-symbols ()
  (interactive)
  (consult-lsp-symbols 'all-workspaces))

(defun my/lsp-treemacs-call-hierarchy ()
  (interactive)
  (lsp-treemacs-call-hierarchy t))

(defun my/lsp-treemacs-references ()
  (interactive)
  (lsp-treemacs-references t))

(defun my/default/insert-file-path ()
  (interactive)
  (+default/insert-file-path t))

;; (defun my/evil-ex ()
;;   (interactive)
;;   (evil-ex "R!echo "))

(defun my/consult-line-multi ()
  (interactive)
  (consult-line-multi 'all-buffers))

(use-package! lsp-execute-code-action
  :commands
  lsp-execute-code-action 
  lsp-organize-imports 
  lsp-symbols 
  lsp-symbols 
  lsp-treemacs-errors-list 
  lsp-treemacs-call-hierarchy 
  lsp-treemacs-call-hierarchy 
  lsp-treemacs-references 
  lsp-treemacs-symbols 
  lsp-command-map 
  lsp-rename)

(use-package! ryo-modal
  :config
  (ryo-modal-keys
    ("SPC"
     ((";"   pp-eval-expression :name "Eval expression")
      (":"   execute-extended-command :name "M-x")
      ("x"   doom/open-scratch-buffer :name "Pop up scratch buffer")
      ("X"   org-capture :name "Org Capture")
      ("u"   universal-argument :name "Universal argument")
      ;; ("w"   evil-window-map :name "window")
      ("h"   help-map :name "help")

      ;; :ui popup
      ("~"   +popup/toggle :name "Toggle last popup")
      ("."   find-file :name "Find file")
      (","   switch-to-buffer :name "Switch buffer")

      ;; :ui workspaces
      (","   persp-switch-to-buffer :name "Switch workspace buffer")
      ("<"   switch-to-buffer :name "Switch buffer")
      ;; ("`"   evil-switch-to-windows-last-buffer :name "Switch to last buffer")
      ("'"   vertico-repeat :name "Resume last search")
      ("*"   +default/search-project-for-symbol-at-point :name "Search for symbol in project")
      ("/"   +default/search-project :name "Search project")
      ("SPC" projectile-find-file :name "Find file in project")
      ("RET" bookmark-jump :name "Jump to bookmark")
      ("e" +eval/line-or-region :name "Evaluate line/region")
      ("a" embark-act :name "Actions")
      ;; ("l" "<localleader>")
      ;; ("!" "checkers")
      ("TAB" (("TAB" +workspace/display :name "Display tab bar")
              ("."   +workspace/switch-to :name "Switch workspace")
              ("`"   +workspace/other :name "Switch to last workspace")
              ("n"   +workspace/new :name "New workspace")
              ("N"   +workspace/new-named :name "New named workspace")
              ("l"   +workspace/load :name "Load workspace from file")
              ("s"   +workspace/save :name "Save workspace to file")
              ("x"   +workspace/kill-session :name "Delete session")
              ("d"   +workspace/delete :name "Delete this workspace")
              ("r"   +workspace/rename :name "Rename workspace")
              ("R"   +workspace/restore-last-session :name "Restore last session")
              ("]"   +workspace/switch-right :name "Next workspace")
              ("["   +workspace/switch-left :name "Previous workspace")
              ("1"   +workspace/switch-to-0 :name "Switch to 1st workspace")
              ("2"   +workspace/switch-to-1 :name "Switch to 2nd workspace")
              ("3"   +workspace/switch-to-2 :name "Switch to 3rd workspace")
              ("4"   +workspace/switch-to-3 :name "Switch to 4th workspace")
              ("5"   +workspace/switch-to-4 :name "Switch to 5th workspace")
              ("6"   +workspace/switch-to-5 :name "Switch to 6th workspace")
              ("7"   +workspace/switch-to-6 :name "Switch to 7th workspace")
              ("8"   +workspace/switch-to-7 :name "Switch to 8th workspace")
              ("9"   +workspace/switch-to-8 :name "Switch to 9th workspace")
              ("0"   +workspace/switch-to-final :name "Switch to final workspace"))
            :name "workspace")
      ("b" (("-" doom/toggle-narrow-buffer :name "Toggle narrowing")
            ("[" previous-buffer :name "Previous buffer")
            ("]" next-buffer :name "Next buffer")
            ("b" persp-switch-to-buffer :name "Switch workspace buffer")
            ("B" switch-to-buffer :name "Switch buffer")
            ("I" +ibuffer/open-for-current-workspace :name "ibuffer workspace")
            ("b" switch-to-buffer :name "Switch buffer")
            ("c" clone-indirect-buffer :name "Clone buffer")
            ("C" clone-indirect-buffer-other-window :name "Clone buffer other window")
            ("d" kill-current-buffer :name "Kill buffer")
            ("i" ibuffer :name "ibuffer")
            ("k" kill-current-buffer :name "Kill buffer")
            ("K" doom/kill-all-buffers :name "Kill all buffers")
            ("l" previous-buffer :name "Switch to last buffer")
            ;; ("l" switch-to-prev-buffer :name "Switch to last buffer")
            ("m" bookmark-set :name "Set bookmark")
            ("M" bookmark-delete :name "Delete bookmark")
            ("n" next-buffer :name "Next buffer")
            ;; ("N" evil-buffer-new :name "New empty buffer")
            ("O" doom/kill-other-buffers :name "Kill other buffers")
            ("p" previous-buffer :name "Previous buffer")
            ("r" revert-buffer :name "Revert buffer")
            ("R" rename-buffer :name "Rename buffer")
            ("s" basic-save-buffer :name "Save buffer")
            ("S" save-some-buffers :name "Save all buffers")
            ("u" doom/sudo-save-buffer :name "Save buffer as root")
            ("x" doom/open-scratch-buffer :name "Pop up scratch buffer")
            ("X" doom/switch-to-scratch-buffer :name "Switch to scratch buffer")
            ("y" +default/yank-buffer-contents :name "Yank buffer")
            ("z" bury-buffer :name "Bury buffer")
            ("Z" doom/kill-buried-buffers :name "Kill buried buffers"))
          :name "buffer")
      ("c" (("a" lsp-execute-code-action :name "LSP Execute code action")
            ("o" lsp-organize-imports :name "LSP Organize imports")
            ("j" consult-lsp-symbols :name "Jump to symbol in current workspace")
            ("J" my/consult-lsp-symbols :name "Jump to symbol in any workspace")
            ("X" lsp-treemacs-errors-list :name "Errors list")
            ("y" lsp-treemacs-call-hierarchy :name "Incoming call hierarchy")
            ("Y" my/lsp-treemacs-call-hierarchy :name "Outgoing call hierarchy")
            ("R" my/lsp-treemacs-references :name "References tree")
            ("S" lsp-treemacs-symbols :name "Symbols")
            ("l" +default/lsp-command-map :name "LSP")
            ("r" lsp-rename :name "LSP Rename")
            ("c" compile :name "Compile")
            ("C" recompile :name "Recompile")
            ("d" +lookup/definition :name "Jump to definition")
            ("D" +lookup/references :name "Jump to references")
            ("e" +eval/buffer-or-region :name "Evaluate buffer/region")
            ;; ("E" +eval:replace-region :name "Evaluate & replace region")
            ("f" +format/region-or-buffer :name "Format buffer/region")
            ("i" +lookup/implementations :name "Find implementations")
            ("k" +lookup/documentation :name "Jump to documentation")
            ("s" +eval/send-region-to-repl :name "Send to repl")
            ("t" +lookup/type-definition :name "Find type definition")
            ("w" delete-trailing-whitespace :name "Delete trailing whitespace")
            ("W" doom/delete-trailing-newlines :name "Delete trailing newlines")
            ("x" +default/diagnostics :name "List errors"))
          :name "code")
      ("f" (("c" editorconfig-find-current-editorconfig :name "Open project editorconfig")
            ("C" doom/copy-this-file :name "Copy this file")
            ("d" +default/dired :name "Find directory")
            ("D" doom/delete-this-file :name "Delete this file")
            ("e" doom/find-file-in-emacsd :name "Find file in emacs.d")
            ("E" doom/browse-in-emacsd :name "Browse emacs.d")
            ("f" find-file :name "Find file")
            ("F" +default/find-file-under-here :name "Find file from here")
            ("l" locate :name "Locate file")
            ("p" doom/find-file-in-private-config :name "Find file in private config")
            ("P" doom/open-private-config :name "Browse private config")
            ("r" recentf-open-files :name "Recent files")
            ("R" doom/move-this-file :name "Rename/move file")
            ("s" save-buffer :name "Save file")
            ("S" write-file :name "Save file as...")
            ("u" doom/sudo-find-file :name "Sudo find file")
            ("U" doom/sudo-this-file :name "Sudo this file")
            ("y" +default/yank-buffer-path :name "Yank file path")
            ("Y" +default/yank-buffer-path-relative-to-project :name "Yank file path from project"))
          :name "file")
      ("g" (("R" vc-revert :name "Revert file")
            ("y" +vc/browse-at-remote-kill :name "Copy link to remote")
            ("Y" +vc/browse-at-remote-kill-homepage :name "Copy link to homepage")
            ; :ui vc-gutter
            ("r" +vc-gutter/revert-hunk :name "Revert hunk at point")
            ("s" +vc-gutter/stage-hunk :name "stage hunk at point")
            ("t" git-timemachine-toggle :name "Git time machine")
            ("]" +vc-gutter/next-hunk :name "Jump to next hunk")
            ("[" +vc-gutter/previous-hunk :name "Jump to previous hunk")
            ;; :tools magit
            ("/" magit-dispatch :name "Magit dispatch")
            ("." magit-file-dispatch :name "Magit file dispatch")
            ("'" forge-dispatch :name "Forge dispatch")
            ("b" magit-branch-checkout :name "Magit switch branch")
            ("g" magit-status :name "Magit status")
            ("G" magit-status-here :name "Magit status here")
            ("D" magit-file-delete :name "Magit file delete")
            ("B" magit-blame-addition :name "Magit blame")
            ("C" magit-clone :name "Magit clone")
            ("F" magit-fetch :name "Magit fetch")
            ("L" magit-log-buffer-file :name "Magit buffer log")
            ("S" magit-stage-file :name "Git stage file")
            ("U" magit-unstage-file :name "Git unstage file")
            ("f" (("f" magit-find-file :name "Find file")
                  ;("g" magit-find-git-config-file :name "Find gitconfig file")
                  ("c" magit-show-commit :name "Find commit")
                  ("i" forge-visit-issue :name "Find issue")
                  ("p" forge-visit-pullreq :name "Find pull request"))
                :name "find")
            ("o" (("o" +vc/browse-at-remote :name "Browse file or region")
                  ("h" +vc/browse-at-remote-homepage :name "Browse homepage")
                  ("r" forge-browse-remote :name "Browse remote")
                  ("c" forge-browse-commit :name "Browse commit")
                  ("i" forge-browse-issue :name "Browse an issue")
                  ("p" forge-browse-pullreq :name "Browse a pull request")
                  ("I" forge-browse-issues :name "Browse issues")
                  ("P" forge-browse-pullreqs :name "Browse pull requests"))
                :name "open in browser")
            ("l" (;("g" +gist:list :name "List gists")
                  ("r" magit-list-repositories :name "List repositories")
                  ("s" magit-list-submodules :name "List submodules")
                  ("i" forge-list-issues :name "List issues")
                  ("p" forge-list-pullreqs :name "List pull requests")
                  ("n" forge-list-notifications :name "List notifications"))
                :name "list")
            ("c" (("r" magit-init :name "Initialize repo")
                  ("R" magit-clone :name "Clone repo")
                  ("c" magit-commit-create :name "Commit")
                  ("f" magit-commit-fixup :name "Fixup")
                  ("b" magit-branch-and-checkout :name "Branch")
                  ("i" forge-create-issue :name "Issue")
                  ("p" forge-create-pullreq :name "Pull request"))
                :name "create"))
            :name "git")
      ("i" (("e" emojify-insert-emoji :name "Emoji")
            ("f" +default/insert-file-path :name "Current file name")
            ("F" my/default/insert-file-path :name "Current file path")
            ;; ("p" my/evil-ex :name "Evil ex path")
            ;; ("r" evil-show-registers :name "From evil register")
            ("s" yas-insert-snippet :name "Snippet")
            ("u" insert-char :name "Unicode")
            ("y" +default/yank-pop :name "From clipboard"))
          :name "insert")
      ("n" (("*" +default/search-notes-for-symbol-at-point :name "Search notes for symbol")
            ("a" org-agenda :name "Org agenda")
            ;; TODO: (modulep! :lang org +noter)
            ;; TODO: (modulep! :lang org +roam)
            ;; TODO: (modulep! :lang org +roam2)
            ;; TODO: (modulep! :lang org +journal)
            ("c" +org/toggle-last-clock :name "Toggle last org-clock")
            ;; ("C" org-clock-cancel :name "Cancel current org-clock")
            ("f" +default/find-in-notes :name "Find file in notes")
            ("F" +default/browse-notes :name "Browse notes")
            ;; ("l" org-store-link :name "Org store link")
            ("m" org-tags-view :name "Tags search")
            ("n" org-capture :name "Org capture")
            ("N" org-capture-goto-target :name "Goto capture")
            ;; ("o" org-clock-goto :name "Active org-clock")
            ("t" org-todo-list :name "Todo list")
            ("s" +default/org-notes-search :name "Search notes")
            ("S" +default/org-notes-headlines :name "Search org agenda headlines")
            ("v" org-search-view :name "View search")
            ("y" +org/export-to-clipboard :name "Org export to clipboard")
            ("Y" +org/export-to-clipboard-as-rich-text :name "Org export to clipboard as RTF"))
          :name "notes")
      ("o" (("a" (("a" org-agenda :name "Agenda")
                  ("t" org-todo-list :name "Todo list")
                  ("m" org-tags-view :name "Tags search")
                  ("v" org-search-view :name "View search"))
                :name "org agenda")
            ("A"  org-agenda :name "Org agenda")
            ("b"  browse-url-of-file :name "Default browser")
            ;; ("d"  +debugger/start :name "Start debugger")
            ("f"  make-frame :name "New frame")
            ("F"  select-frame-by-name :name "Select frame")
            ("r"  +eval/open-repl-other-window :name "REPL")
            ("R"  +eval/open-repl-same-window :name "REPL (same window)")
            ("-"  dired-jump :name "Dired")
            ("p"  +treemacs/toggle :name "Project sidebar")
            ("P"  treemacs-find-file :name "Find file in project sidebar"))
          :name "open")
      ("p" (("." +default/browse-project :name "Browse project")
            (">" doom/browse-in-other-project :name "Browse other project")
            ("!" projectile-run-shell-command-in-root :name "Run cmd in project root")
            ("&" projectile-run-async-shell-command-in-root :name "Async cmd in project root")
            ("a" projectile-add-known-project :name "Add new project")
            ("b" projectile-switch-to-buffer :name "Switch to project buffer")
            ("c" projectile-compile-project :name "Compile in project")
            ("C" projectile-repeat-last-command :name "Repeat last command")
            ("d" projectile-remove-known-project :name "Remove known project")
            ("D" +default/discover-projects :name "Discover projects in folder")
            ("e" projectile-edit-dir-locals :name "Edit project .dir-locals")
            ("f" projectile-find-file :name "Find file in project")
            ("F" doom/find-file-in-other-project :name "Find file in other project")
            ("g" projectile-configure-project :name "Configure project")
            ("i" projectile-invalidate-cache :name "Invalidate project cache")
            ("k" projectile-kill-buffers :name "Kill project buffers")
            ("o" projectile-find-other-file :name "Find other file")
            ("p" projectile-switch-project :name "Switch project")
            ("r" projectile-recentf :name "Find recent project files")
            ("R" projectile-run-project :name "Run project")
            ("s" projectile-save-project-buffers :name "Save project files")
            ("t" magit-todos-list :name "List project todos")
            ("T" projectile-test-project :name "Test project")
            ("x" doom/open-project-scratch-buffer :name "Pop up scratch buffer")
            ("X" doom/switch-to-project-scratch-buffer :name "Switch to scratch buffer"))
          :name "project")
      ("q" (("d" +default/restart-server :name "Restart emacs server")
            ("f" delete-frame :name "Delete frame")
            ("F" doom/kill-all-buffers :name "Clear current frame")
            ("K" save-buffers-kill-emacs :name "Kill Emacs (and daemon)")
            ("q" kill-emacs :name "Quit Emacs")
            ("Q" save-buffers-kill-terminal :name "Quit Emacs without saving")
            ("s" doom/quicksave-session :name "Quick save current session")
            ("l" doom/quickload-session :name "Restore last session")
            ("S" doom/save-session :name "Save session to file")
            ("L" doom/load-session :name "Restore session from file")
            ("r" doom/restart-and-restore :name "Restart & restore Emacs")
            ("R" doom/restart :name "Restart Emacs"))
          :name "quit/session")
      ("s" (("b" +default/search-buffer :name "Search buffer")
            ;; ("B" my/consult-line-multi :name "Search all open buffers")
            ("d" +default/search-cwd :name "Search current directory")
            ("D" +default/search-other-cwd :name "Search other directory")
            ("e" +default/search-emacsd :name "Search .emacs.d")
            ("f" locate :name "Locate file")
            ("i" imenu :name "Jump to symbol")
            ("l" link-hint-open-link :name "Jump to visible link")
            ("L" ffap-menu :name "Jump to link")
            ;; ("j" evil-show-jumps :name "Jump list")
            ("m" bookmark-jump :name "Jump to bookmark")
            ("o" +lookup/online :name "Look up online")
            ("O" +lookup/online-select :name "Look up online (w/ prompt)")
            ;; ("k" +lookup/in-docsets :name "Look up in local docsets")
            ;; ("K" +lookup/in-all-docsets :name "Look up in all docsets")
            ("p" +default/search-project :name "Search project")
            ("P" +default/search-other-project :name "Search other project")
            ;; ("r" evil-show-marks :name "Jump to mark")
            ("s" +default/search-buffer :name "Search buffer")
            ("S" +vertico/search-symbol-at-point :name "Search buffer for thing at point")
            ("t" +lookup/dictionary-definition :name "Dictionary")
            ("T" +lookup/synonyms :name "Thesaurus")
            ;; ("u" vundo :name "Undo history")
            )
          :name "search")
      ("t" (("b" doom-big-font-mode :name "Big mode")
            ("c" global-display-fill-column-indicator-mode :name "Fill Column Indicator")
            ("f" flymake-mode :name "Flymake")
            ;; :checkers syntax
            ("f" flycheck-mode :name "Flycheck")
            ("F" toggle-frame-fullscreen :name "Frame fullscreen")
            ; ("g" evil-goggles-mode :name "Evil goggles")
            ;; :ui indent-guides
            ("i" highlight-indent-guides-mode :name "Indent guides")
            ("I" doom/toggle-indent-style :name "Indent style")
            ("l" doom/toggle-line-numbers :name "Line numbers")
            ("r" read-only-mode :name "Read-only mode")
            ;; :checkers spell +flyspell
            ("s" flyspell-mode :name "Spell checker")
            ("v" visible-mode :name "Visible mode")
            ("w" visual-line-mode :name "Soft line wrapping")
            ;; :editor word-wrap
            ("w" +word-wrap-mode :name "Soft line wrapping")
            ;; :ui zen
            ("z" +zen/toggle :name "Zen mode")
            ("Z" +zen/toggle-fullscreen :name "Zen mode (fullscreen)"))
          :name "toggle")
      ("C-f" (("C-d"     vimish-fold-delete)
              ("C-a C-d" vimish-fold-delete-all)
              ("C-f"     +fold/toggle)
              ("C-a C-f" +fold/close-all)
              ("C-u"     +fold/open)
              ("C-a C-u" +fold/open-all))
            :name "fold")))))
