{ ... }: {
  imports = [
    ./agenix.nix
    ./any-nix-shell.nix
    ./bash.nix
    ./brave.nix
    ./cloudflare-warp.nix
    ./code.nix
    ./direnv.nix
    ./electron.nix
    ./dunst.nix
    ./emacs.nix
    ./fish.nix
    ./fonts.nix
    ./git.nix
    ./jamesdsp.nix
    ./keychain.nix
    ./kitty.nix
    ./loopback-toggle.nix
    ./micro.nix
    ./microsoft-edge.nix
    ./obs.nix
    ./onedrive.nix
    ./pacman.nix
    ./podman.nix
    ./qview.nix
    ./rclone.nix
    ./retroarch.nix
    ./rofi.nix
    ./steam.nix
    ./sway.nix
    ./systemd.nix
    ./telegram.nix
    ./theme.nix
    ./udiskie.nix
    ./waybar.nix
    ./xdg.nix
    ./zoxide.nix
  ];
}
