# REVIEW: https://danth.github.io/stylix/installation.html
{ ... }: {
  imports = [
    ./agenix.nix
    ./any-nix-shell.nix
    ./autorandr.nix
    ./bash.nix
    ./brave.nix
    ./cloudflare-warp.nix
    ./code.nix
    ./copy-file.nix
    ./direnv.nix
    ./dunst.nix
    ./emacs.nix
    ./feh.nix
    ./fish.nix
    ./fontconfig.nix
    ./fonts.nix
    ./i3wm.nix
    ./jamesdsp.nix
    ./keychain.nix
    ./kitty.nix
    ./loopback-toggle.nix
    ./micro.nix
    ./microsoft-edge.nix
    ./obs.nix
    ./pacman.nix
    ./picom.nix
    ./podman.nix
    ./polybar.nix
    ./qview.nix
    ./rclone.nix
    ./rofi.nix
    ./scaling.nix
    ./screenshot.nix
    ./shell.nix
    ./steam.nix
    ./telegram.nix
    ./themes.nix
    ./udiskie.nix
    ./xdg.nix
    ./xorg.nix
    ./zoxide.nix
  ];
}
