if (Test-Path alias:arch) { Remove-Item -Path alias:arch }
if (Test-Path alias:base32) { Remove-Item -Path alias:base32 }
if (Test-Path alias:base64) { Remove-Item -Path alias:base64 }
if (Test-Path alias:basename) { Remove-Item -Path alias:basename -Scop}
if (Test-Path alias:cat) { Remove-Item -Path alias:cat }
if (Test-Path alias:cksum) { Remove-Item -Path alias:cksum }
if (Test-Path alias:comm) { Remove-Item -Path alias:comm }
if (Test-Path alias:cp) { Remove-Item -Path alias:cp }
if (Test-Path alias:curl) { Remove-Item -Path alias:curl }
if (Test-Path alias:cut) { Remove-Item -Path alias:cut }
if (Test-Path alias:date) { Remove-Item -Path alias:date }
if (Test-Path alias:df) { Remove-Item -Path alias:df }
if (Test-Path alias:dircolors) { Remove-Item -Path alias:dircolors -Scop}
if (Test-Path alias:dirname) { Remove-Item -Path alias:dirname }
if (Test-Path alias:echo) { Remove-Item -Path alias:echo }
if (Test-Path alias:env) { Remove-Item -Path alias:env }
if (Test-Path alias:expand) { Remove-Item -Path alias:expand }
if (Test-Path alias:expr) { Remove-Item -Path alias:expr }
if (Test-Path alias:factor) { Remove-Item -Path alias:factor }
if (Test-Path alias:false) { Remove-Item -Path alias:false }
if (Test-Path alias:fmt) { Remove-Item -Path alias:fmt }
if (Test-Path alias:fold) { Remove-Item -Path alias:fold }
if (Test-Path alias:hashsum) { Remove-Item -Path alias:hashsum }
if (Test-Path alias:head) { Remove-Item -Path alias:head }
if (Test-Path alias:hostname) { Remove-Item -Path alias:hostname -Scop}
if (Test-Path alias:join) { Remove-Item -Path alias:join }
if (Test-Path alias:link) { Remove-Item -Path alias:link }
if (Test-Path alias:ln) { Remove-Item -Path alias:ln }
if (Test-Path alias:ls) { Remove-Item -Path alias:ls }
if (Test-Path alias:md5sum) { Remove-Item -Path alias:md5sum }
if (Test-Path alias:mkdir) { Remove-Item -Path alias:mkdir }
if (Test-Path alias:mktemp) { Remove-Item -Path alias:mktemp }
if (Test-Path alias:more) { Remove-Item -Path alias:more }
if (Test-Path alias:mv) { Remove-Item -Path alias:mv }
if (Test-Path alias:nl) { Remove-Item -Path alias:nl }
if (Test-Path alias:nproc) { Remove-Item -Path alias:nproc }
if (Test-Path alias:od) { Remove-Item -Path alias:od }
if (Test-Path alias:paste) { Remove-Item -Path alias:paste }
if (Test-Path alias:printenv) { Remove-Item -Path alias:printenv -Scop}
if (Test-Path alias:printf) { Remove-Item -Path alias:printf }
if (Test-Path alias:ps) { Remove-Item -Path alias:ps }
if (Test-Path alias:ptx) { Remove-Item -Path alias:ptx }
if (Test-Path alias:pwd) { Remove-Item -Path alias:pwd }
if (Test-Path alias:readlink) { Remove-Item -Path alias:readlink -Scop}
if (Test-Path alias:realpath) { Remove-Item -Path alias:realpath -Scop}
if (Test-Path alias:relpath) { Remove-Item -Path alias:relpath }
if (Test-Path alias:rm) { Remove-Item -Path alias:rm }
if (Test-Path alias:rmdir) { Remove-Item -Path alias:rmdir }
if (Test-Path alias:seq) { Remove-Item -Path alias:seq }
if (Test-Path alias:sha1sum) { Remove-Item -Path alias:sha1sum }
if (Test-Path alias:sha224sum) { Remove-Item -Path alias:sha224sum -Scop}
if (Test-Path alias:sha256sum) { Remove-Item -Path alias:sha256sum -Scop}
if (Test-Path alias:sha3-224sum) { Remove-Item -Path alias:sha3-224sum -Scop}
if (Test-Path alias:sha3-256sum) { Remove-Item -Path alias:sha3-256sum -Scop}
if (Test-Path alias:sha3-384sum) { Remove-Item -Path alias:sha3-384sum -Scop}
if (Test-Path alias:sha3-512sum) { Remove-Item -Path alias:sha3-512sum -Scop}
if (Test-Path alias:sha384sum) { Remove-Item -Path alias:sha384sum -Scop}
if (Test-Path alias:sha3sum) { Remove-Item -Path alias:sha3sum }
if (Test-Path alias:sha512sum) { Remove-Item -Path alias:sha512sum -Scop}
if (Test-Path alias:shake128sum) { Remove-Item -Path alias:shake128sum -Scop}
if (Test-Path alias:shake256sum) { Remove-Item -Path alias:shake256sum -Scop}
if (Test-Path alias:shred) { Remove-Item -Path alias:shred }
if (Test-Path alias:shuf) { Remove-Item -Path alias:shuf }
if (Test-Path alias:split) { Remove-Item -Path alias:split }
if (Test-Path alias:sum) { Remove-Item -Path alias:sum }
if (Test-Path alias:sync) { Remove-Item -Path alias:sync }
if (Test-Path alias:tac) { Remove-Item -Path alias:tac }
if (Test-Path alias:tail) { Remove-Item -Path alias:tail }
if (Test-Path alias:test) { Remove-Item -Path alias:test }
if (Test-Path alias:touch) { Remove-Item -Path alias:touch }
if (Test-Path alias:tr) { Remove-Item -Path alias:tr }
if (Test-Path alias:true) { Remove-Item -Path alias:true }
if (Test-Path alias:truncate) { Remove-Item -Path alias:truncate -Scop}
if (Test-Path alias:tsort) { Remove-Item -Path alias:tsort }
if (Test-Path alias:unexpand) { Remove-Item -Path alias:unexpand -Scop}
if (Test-Path alias:uniq) { Remove-Item -Path alias:uniq }
if (Test-Path alias:wc) { Remove-Item -Path alias:wc }
if (Test-Path alias:whoami) { Remove-Item -Path alias:whoami }
if (Test-Path alias:yes) { Remove-Item -Path alias:yes }
