(defun set-mark-sexp ()
  (interactive)
  (deactivate-mark)
  (backward-char)
  (sp-forward-sexp)
  (sp-backward-sexp)
  (sp-mark-sexp)
  (exchange-point-and-mark))

(defun toggle-mark ()
  (interactive)
  (if (region-active-p)
      (deactivate-mark)
      (set-mark (point))))

(defun mark-whole-line-to-next (arg)
  (interactive "p")
  (end-of-line)
  (unless (use-region-p)
    (set-mark (line-beginning-position)))
  (forward-line arg))

(defun mark-whole-line-to-previous (arg)
  (interactive "p")
  (mark-whole-line-to-next (- (or arg 1))))

(provide 'text-object)
