# gruvbox dark:              "#282828"
# gruvbox dark hard:         "#1B1B1B"
# popping and locking:       "#181921" "#1D2021"
# popping and locking black: "#000000" "#1D2021"

general:
  show_floating_on_top: false
  
gaps:
  inner_gap: 24 # 32 # 24 # 16 # 8 
  outer_gap: 24 # 32 # 24 # 16 # 8 

bar:
  height: "28px"
  position: "top"
  opacity: 1.0
  background: "transparent"
  foreground: "#EBDBB2" # popping and locking and gruvbox
  # foreground: "#F2E5BC" # popping and locking black (cursor)
  font_family: "Cascadia Code"
  font_size: "11px"
  border_width: "0px 0px 1px 0px"
  # border_color: "#282828" # gruvbox dark
  # border_color: "#1B1B1B" # gruvbox dark hard
  # border_color: "#181921" # popping and locking
  border_color: "#000000" # popping and locking black
  padding: "2px 4px"

  components_left:
    - type: "workspaces"
      # focused_workspace_background: "#282828" # gruvbox dark
      # focused_workspace_background: "#1B1B1B" # gruvbox dark hard
      # focused_workspace_background: "#181921" # popping and locking
      focused_workspace_background: "#000000" # popping and locking black
      displayed_workspace_background: "transparent"
      default_workspace_background: "transparent"
      default_workspace_foreground: "#A89984"
      margin: "0 6px 0 0"
    - type: "binding mode"
      # background: "#282828" # gruvbox dark
      # background: "#1B1B1B" # gruvbox dark hard
      # background: "#181921" # popping and locking
      background: "#000000" # popping and locking black
      margin: "0 4px"
      padding: "0 6px"

  components_center:
    - type: "window title"
      margin: "0 4px"

  components_right:
    - type: "tiling direction"
      # background: "#282828" # gruvbox dark
      # background: "#1B1B1B" # gruvbox dark hard
      # background: "#181921" # popping and locking
      background: "#000000" # popping and locking black
      margin: "0 4px"
      padding: "0 6px"
    - type: "battery"
      label_draining: "{battery_level}% ▼ "
      label_power_saver: "{battery_level}% ↯ "
      label_charging: "{battery_level}% ▲ "
      margin: "0 4px"
    - type: "clock"
      time_formatting: "dddd · yyyy-MM-dd · HH:mm:ss"
      margin: "0 6px 0 0px"

workspaces:
  - name: "1"
    bind_to_monitor: 2
  - name: "2"
    bind_to_monitor: 2
  - name: "3"
    bind_to_monitor: 2
  - name: "4"
    bind_to_monitor: 2
  - name: "5"
    bind_to_monitor: 2
  - name: "6"
    bind_to_monitor: 1
  - name: "7"
    bind_to_monitor: 1
  - name: "8"
    bind_to_monitor: 1
  - name: "9"
    bind_to_monitor: 1
  - name: "0"
    bind_to_monitor: 1

window_rules:
  # make all float by default 
  - command: "set floating"
    match_process_name: "*"

  # ignore windows that require admin privileges to manage:
  - command: "ignore"
    match_process_name: "Taskmgr"
  - command: "ignore"
    match_process_name: "regedit"
  - command: "ignore"
    match_process_name: "PowerToys.Settings"

  # some tile by default
  - command: "set tiling"
    match_title: "/.*Visual Studio Code$/"
  - command: "set tiling"
    match_process_name: "WindowsTerminal"
  - command: "set tiling"
    match_process_name: "emacs"
  - command: "set tiling"
    match_process_name: "vcxsrv.exe"
  - command: "set tiling"
    match_process_name: "Aseprite"
  - command: "set tiling"
    match_title: "/.+\\s\\- Thorium/"
  - command: "set tiling"
    match_title: "/.+\\s\\- Microsoft Edge/"
  - command: "set tiling"
    match_title: "/.+\\s\\- Notepad/"
  - command: "set tiling"
    match_title: "/.+\\s\\- Notepad\\+\\+/"

  # floating by default:
  - command: "set floating"
    match_class_name: "#32770" # system dialogs

  # fix border for some apps:
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

  # generated from https://raw.githubusercontent.com/LGUG2Z/komorebi-application-specific-configuration/master/applications.yaml
  # with https://github.com/lars-berger/GlazeWM/issues/105#issuecomment-1235289741
  - command: set floating
    match_process_name: 1Password
  - command: set floating
    match_class_name: AbletonVstPlugClass
  - command: set floating
    match_class_name: Vst3PlugWindow
  - command: set floating
    match_title: Window Spy
  - command: set floating
    match_process_name: Bloxstrap
  - command: set floating
    match_title: Calculator
  - command: set floating
    match_process_name: CredentialUIBroker
  - command: set floating
    match_class_name: TApplication
  - command: set floating
    match_class_name: TWizardForm
  - command: set floating
    match_process_name: Dropbox
  - command: set floating
    match_process_name: Elephicon
  - command: set floating
    match_process_name: Camera Hub
  - command: set floating
    match_process_name: ControlCenter
  - command: set floating
    match_process_name: WaveLink
  - command: set floating
    match_class_name: Chrome_RenderWidgetHostHWND
  - command: set floating
    match_class_name: SunAwtDialog
  - command: set floating
    match_process_name: keyviz
  - command: set floating
    match_process_name: LogiBolt
  - command: set floating
    match_process_name: LogiTune
  - command: set floating
    match_process_name: LogiOptionsUI
  - command: set floating
    match_class_name: _WwB
  - command: set floating
    match_class_name: _WwB
  - command: set floating
    match_process_name: MSPCManager
  - command: set floating
    match_class_name: _WwB
  - command: set floating
    match_title: Microsoft Teams Notification
  - command: set floating
    match_title: Microsoft Teams Call
  - command: set floating
    match_class_name: _WwB
  - command: set floating
    match_class_name: MozillaTaskbarPreviewClass
  - command: set floating
    match_process_name: NohBoard
  - command: set floating
    match_process_name: Paradox Launcher
  - command: set floating
    match_process_name: PowerToys.ColorPickerUI
  - command: set floating
    match_process_name: PowerToys.ImageResizer
  - command: set floating
    match_process_name: ProcessHacker
  - command: set floating
    match_class_name: SunAwtDialog
  - command: set floating
    match_process_name: QuickLook
  - command: set floating
    match_process_name: RepoZ
  - command: set floating
    match_class_name: SunAwtDialog
  - command: set floating
    match_process_name: RoundedTB
  - command: set floating
    match_process_name: sideloadly
  - command: set floating
    match_class_name: Chrome_RenderWidgetHostHWND
  - command: set floating
    match_class_name: Chrome_RenderWidgetHostHWND
  - command: set floating
    match_class_name: obj_App
  - command: set floating
    match_class_name: obj_Form
  - command: set floating
    match_process_name: SystemInformer
  - command: set floating
    match_class_name: Shell_Dialog
  - command: set floating
    match_class_name: TaskManagerWindow
  - command: set floating
    match_process_name: tcconfig
  - command: set floating
    match_process_name: TranslucentTB
  - command: set floating
    match_class_name: OperationStatusWindow
  - command: set floating
    match_title: Control Panel
  - command: set floating
    match_process_name: msiexec
  - command: set floating
    match_title: Hotkey sink
  - command: set floating
    match_process_name: Zoom
  - command: set floating
    match_process_name: paintdotnet
  - command: set floating
    match_process_name: pinentry
  - command: set floating
    match_process_name: ueli

binding_modes:

  # resize mode:
  - name: "resize"
    keybindings:
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      - command: "binding mode none"
        bindings: ["Escape", "Enter", "Space"]

keybindings:
  #
  # basics
  #

  # focus
  - command: "focus left"
    bindings: ["LWin+Control+Left"]
  - command: "focus right"
    bindings: ["LWin+Control+Right"]
  - command: "focus up"
    bindings: ["LWin+Control+Up"]
  - command: "focus down"
    bindings: ["LWin+Control+Down"]

  # move
  - command: "move left"
    bindings: ["LWin+Control+Shift+Left"]
  - command: "move right"
    bindings: ["LWin+Control+Shift+Right"]
  - command: "move up"
    bindings: ["LWin+Control+Shift+Up"]
  - command: "move down"
    bindings: ["LWin+Control+Shift+Down"]

  # workspace focus
  - command: "focus workspace 1"
    binding: "LWin+Control+1"
  - command: "focus workspace 2"
    binding: "LWin+Control+2"
  - command: "focus workspace 3"
    binding: "LWin+Control+3"
  - command: "focus workspace 4"
    binding: "LWin+Control+4"
  - command: "focus workspace 5"
    binding: "LWin+Control+5"
  - command: "focus workspace 6"
    binding: "LWin+Control+6"
  - command: "focus workspace 7"
    binding: "LWin+Control+7"
  - command: "focus workspace 8"
    binding: "LWin+Control+8"
  - command: "focus workspace 9"
    binding: "LWin+Control+9"
  - command: "focus workspace 0"
    binding: "LWin+Control+0"

  # focus last workspace with focus
  - command: "focus workspace recent"
    binding: "LWin+Control+Y"

  # move to workspace focus
  - command: "move to workspace 1"
    binding: "LWin+Control+Shift+1"
  - command: "move to workspace 2"
    binding: "LWin+Control+Shift+2"
  - command: "move to workspace 3"
    binding: "LWin+Control+Shift+3"
  - command: "move to workspace 4"
    binding: "LWin+Control+Shift+4"
  - command: "move to workspace 5"
    binding: "LWin+Control+Shift+5"
  - command: "move to workspace 6"
    binding: "LWin+Control+Shift+6"
  - command: "move to workspace 7"
    binding: "LWin+Control+Shift+7"
  - command: "move to workspace 8"
    binding: "LWin+Control+Shift+8"
  - command: "move to workspace 9"
    binding: "LWin+Control+Shift+9"
  - command: "move to workspace 0"
    binding: "LWin+Control+Shift+0"

  #
  # mode swap
  #

  # to resize mode
  - command: "binding mode resize" # originally "toggle focus mode"
    binding: "LWin+Control+S" # stop opening narrator mode
  
  #
  # decoration actions
  #

  # minimize window
  - command: "set minimized"
    binding: "LWin+Control+M"

  # toggle maximized window
  - command: "toggle maximized"
    binding: "LWin+Control+X"

  # close window
  - command: "close"
    binding: "LWin+Control+C"

  #
  # tiling misc
  #

  # toggle floating focus
  - command: "toggle focus mode"
    binding: "LWin+Control+Space"
  
  # toggle floating window
  - command: "toggle floating"
    binding: "LWin+Control+F"
    
  # tiling direction vertical
  - command: "tiling direction toggle"
    binding: "LWin+Control+V"

  #
  # glazewm
  # 

  # reload
  - command: "reload config"
    binding: "LWin+Control+Shift+R"

  # quit
  - command: "exit wm"
    binding: "LWin+Control+Shift+Escape"

  #
  # launchers
  #

  # launch explorer
  - command: "exec explorer"
    binding: "LWin+Control+E"

  # launch terminal (wsl profile)
  - command: exec wt --profile "{8e510365-d81d-426c-9b28-dfb96a7a6a85}"
    binding: "LWin+Control+Back"

  # launch terminal (default profile)
  - command: exec wt
    binding: "LWin+Control+T"

  # launch screenclip
  - command: "exec explorer ms-screenclip:"
    binding: "LWin+Control+Shift+S"

  # launch main ide
  - command: exec 'D:\Users\kress\scoop\apps\vscode\current\Code.exe'
    binding: "LWin+Control+D"

  # launch browser'
  - command: exec 'D:\'Users\kress\scoop\apps\thorium-avx2\current\thorium.exe' --allow-outdated-plugins --disable-logging --disable-breakpad --enable-experimental-web-platform-features --new-canvas-2d-api
    binding: "LWin+Control+B"
